theme: jekyll-theme-leap-day
show_downloads: false
title: Efficient Git
description: Use git efficiently on your projects and avoid usual mistakes
menu:
  - { label: Overview, url: /efficient-git/index}
  - { label: Teamwork, url: /efficient-git/teamwork}
  - { label: Gitflow, url: /efficient-git/gitflow}
  - { label: Merge, url: /efficient-git/merge}
  - { label: Tag, url: /efficient-git/tag}
  - { label: Versioning, url: /efficient-git/version}