theme: jekyll-theme-leap-day
title: Efficient Git
description: Use git efficiently on your project and avoid usual mistakes
menu:
  - { label: Overview, url: index}
  - { label: Team work, url: teamwork}
  - { label: Merge, url: merge}
  - { label: Tag, url: tag}
  - { label: Gitflow, url: gitflow}
  - { label: Version, url: version}